baseURL = "https://wizardly-blackwell-9d110c.netlify.app/"
languageCode = "en-us"
title = "Brittany's Hugo Site"
theme = "hugo-theme-m10c-master"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[params]
[[menu.main]]
name = "Introduction"
weight = 1
url = "/IntroductionPost/"

[[menu.main]]
name = "Annotated Definitions"
weight = 1
url = "/AnnotatedDefinitions/"

[[menu.main]]
name = "Resource Guide"
weight = 1
url = "/ResourceGuide/"

[[menu.main]]
name = "Walkthrough"
weight = 1
url = "/Walkthrough/"

